### ISSUE TITLE
Launch-VI must be checked for existence

### ISSUE THREAD

**Issue by rose-a** [JamesMc86/LabVIEW-CLI#11]
Launch-VI is resolved to something stupid if left out (ie. if you just type `labview-cli -v`)

Maybe one could use the *Lists* and *Arrays* features of the CommandLineParser lib to parse the whole argument string (especially Launch-VI and LV-Arguments) with the library methods (see https://github.com/gsscoder/commandline/wiki/Mapping-Properties-To-Options).

This would also help generating a proper help screen.

**Comment by JamesMc86** [comment]
Thats great - just had someone else mention this as well. Looks like you are already on the case but let me know if you need any input
