### ISSUE TITLE
Outdated CLI app version

### ISSUE THREAD

**Issue by nephe** [JamesMc86/LabVIEW-CLI#19]
Please add newest CLI version to releases. I saw that kill option is provided but executable with that functionality is missing.

**Comment by JamesMc86** [comment]
Hi Nephe,

Sure I'll sort this by the end of the week for you

**Comment by chinghwayu** [comment]
@nephe, give this a try in the meantime:
https://github.com/rose-a/LabVIEW-CLI/releases/tag/v1.4.0-beta

**Comment by JamesMc86** [comment]
Updated here as well - sorry had a change of laptop so all my environments were out!

It's now at https://github.com/JamesMc86/LabVIEW-CLI/releases/tag/v1.4.0 (but no changes other than from the previous link anyway)
