### ISSUE TITLE
Auto-detection of free ports

### ISSUE THREAD

**Issue by JamesMc86** [JamesMc86/LabVIEW-CLI#2]
If the port we try and use fails, we should attempt additional port numbers to a limited range.

**Comment by chinghwayu** [comment]
I would actually vote to randomize the port number by default in the dynamic range of 49152-65535. Retry until available.

This would tremendously increasing the scalability of this tool - launch multiple instances and/or versions of LabVIEW.

**Comment by JamesMc86** [comment]
Fixed in pull request #7 thanks @chinghwayu!
