### ISSUE TITLE
Add "disabled" property to mute errors when calling VIs manually

### ISSUE THREAD

**Issue by joerghampel** [JamesMc86/LabVIEW-CLI#25]
If I call my build VIs manually, either directly from the development environment or via my build GUI, the "Start CLI Interface.vi" throws an error (scan from string fails because list of parameters is empty). What I would like to be able to do is tell the CLI interface that it should just ignore all following calls and not throw any errors, so I don't have to disable all of the occurances of the "Write String.vi"s all over my code.
![cli-state](https://user-images.githubusercontent.com/7075830/27011333-9f7070f2-4eb9-11e7-9962-1585edb67be4.png)

**Comment by JamesMc86** [comment]
1. Definitely, have a better handling of the connect case to give a specific error and perhaps a Boolean flag you can work from.
2. I am slightly concerned about having the API disable itself in the case of a failed connection. Whilst I appreciate it would be more convenient if it did, this feels like something that would be better handled at the application layer.

Happy to get the opinion of others though, is this something that makes sense to have in the library (point 2)?

**Comment by joerghampel** [comment]
I didn't mean it should disable itself automatically, my thought was to have just the property inside the class so I can set it whenever I want. 

I can see two alternatives for me: Wrap all "Write String.vi"s into a subVI with a case structure inside (but I still would have to wire the CLI reference and the enable/disable info), or create a subclass that implements the disable feature.

**Comment by joerghampel** [comment]
As per our discussion yesterday, I will implement a wrapper class for the functionality I'd like to see. It will enable me to either output to the command line if called via CLI or to a GUI if called from my LabVIEW build tool.
