### ISSUE TITLE
Can't run echo test with x64 flag

### ISSUE THREAD

**Issue by hoffiz** [JamesMc86/LabVIEW-CLI#27]
New to LabVIEW-CLI. I'm following a getting started guide and got stuck trying to run the echo test example with 2017 64 bits.

The error returns:

_LabVIEW version "2017 64bit" not found!
Available LabVIEW versions are:
2016 f2, 32bit
2017, 32bit
2016 f2, 32bit
2017, 32bit_

On the other hand, I can successfully run the echo example in 32 bits.

**Comment by JamesMc86** [comment]
Hi,

I'll try to take a look this week - obviously something isn't quite right from the list!

Cheers,

James M

________________________________

**Comment by JamesMc86** [comment]
Hi Hoffiz,

I think I see a bug in the 64 bit support when we scan the versions from the registry. I don't have a 64 bit version installed right now but I'll get one installed on a VM and see how it looks

**Comment by JamesMc86** [comment]
Actually, if it is easy could you also run it with the -v (verbose mode) flag. This should print out the versions detected and the installation paths. If they are different paths even though it says they are all 32 bit I should be able to fix it over the next week.

**Comment by hoffiz** [comment]
Hi James, sorry I did not reply sooner. This is sort of a personal project in the SE team. I see that you already closed it but I can test it again if you would like to.

**Comment by JamesMc86** [comment]
No need - I managed to recreate the issue and added the fix. You can install v1.5.0 from the releases page at https://github.com/JamesMc86/LabVIEW-CLI/releases/tag/v1.5.0 and it will then work.

**Comment by hoffiz** [comment]
Jut did and the echo test works on windows 10 64bits and LabVIEW 64 bit works. Thanks for your help!
