### ISSUE TITLE
Have a getting started guide

### ISSUE THREAD

**Issue by JamesMc86** [JamesMc86/LabVIEW-CLI#29]

**Comment by pollockm** [comment]
I have something akin to this over here: https://github.com/LabVIEW-DCAF/buildsystem/blob/master/docs/CLI%20Tutorial.pdf

**Comment by hoffiz** [comment]
@pollockm this document could use some addition for the newbies like me. For example, LabVIEW is already using port 808 but it took me a bit to figure that out. I end up changing the port in the xml to port 8081.

**Comment by pollockm** [comment]
@hoffiz - I'll get the source of the document posted so pull requests and issues on it can be registered.

**Comment by JamesMc86** [comment]
Created a pure CLI getting started document as well at https://github.com/JamesMc86/LabVIEW-CLI/wiki/Getting-Started-With-LabVIEW-CLI
