### ISSUE TITLE
Detect If LabVIEW Is Already Running

### ISSUE THREAD

**Issue by JamesMc86** [JamesMc86/LabVIEW-CLI#34]
There is an API that will allow us to detect if LabVIEW is already running but it appears it will require our application to be 64bit in order to support it.

Questions are:

1. Do we mind the application being 64bit? I think it is unlikely to be a problem for most people.
2. Do we add the ability to kill LabVIEW if it is running?

**Comment by JamesMc86** [comment]
Other option is can we build for both and install the correct bitness for the OS?

**Comment by chinghwayu** [comment]
How about building both and then have postinstall determine bitness to launch corresponding installer?

**Comment by joerghampel** [comment]
I use your tool for LabVIEW versions 2013 and newer. All of these versions run on either Win7 64bit or Win10 64bit. BUT: I use only the 32-bit versions of LabVIEW.

Generally, I think the tool should support all possible use cases - perhaps build it for both bitnesses?

**Comment by JamesMc86** [comment]
This will be fixed in v2.0
