### ISSUE TITLE
Not working if only Runtime Engine is installed

### ISSUE THREAD

**Issue by MattGib** [JamesMc86/LabVIEW-CLI#36]
I am calling a compiled Labview executable with the Labview-CLI tool.  It works perfectly on a machine that has both the Labview Runtime and any version of Labview development enviroment.  Unfortunately, it does not work on a computer that has only the Runtime Engine installed. I get this error "No LabVIEW.exe found..."

The problem is the following. Since I am calling an executable there is no need to check for the installed Labview versions and for LabVIEW.exe.  This check should be skipped when the launch program is an exe.

**Comment by JamesMc86** [comment]
Hi Matt,

Thanks for bringing this up. Can I just confirm you have tried with v1.5.1 (https://github.com/JamesMc86/LabVIEW-CLI/releases/tag/v1.5.1) since this fixed an issue with detection that it is a built executable?

**Comment by MattGib** [comment]
Hi James,

Yes I was using V1.5.1.  If it is a built executable it should not check for a Labview version. It just needs to run the executable. As it is, v1.5.1 will return an error if there is no LV Development environment installed.

I fixed the code locally and it resolved the issue.  The new code does not call lvVersion and lvPathFinder() when the launch VI is an exe.  See code below.  

Program.cs
                try
                {
                    string lvPath;
                    if (isExe(options.LaunchVI))
                    {
                        lvPath = null;
                    }
                    else
                    {
                        lvVersion current = LvVersions.CurrentVersion;
                        lvPath = lvPathFinder(options);
                    }

                    launcher = new LvLauncher(options.LaunchVI, lvPath, lvInterface.port, lvArgs);
                    launcher.Exited += Launcher_Exited;
                    launcher.Start();
                }

I also removed the following lines at the beginning of the code: 

Line 27: ~~lvVersion current = LvVersions.CurrentVersion;~~ 
Line 48: ~~LvVersions.Scan();~~

Let me know if you want me to check in the code.

**Comment by JamesMc86** [comment]
Just going to take a quick look now - my feeling is that is a large change when really the better behaviour is it doesn't care if there is no LabVIEW. The scan can still run it just should continue regardless.

**Comment by JamesMc86** [comment]
OK I have a fix for you which I'm buiding as v1.5.2. This means that pathfinder returns a blank path if none is found and then we throw an error only if we try and launch a non-exe VI.

I've tested your use case here and it seems to do the trick.

It's live at https://github.com/JamesMc86/LabVIEW-CLI/releases/tag/v1.5.2

**Comment by MattGib** [comment]
Awesome.  Thank you for the quick turn around on this. I will test it shortly and let you know if there are any issues.
