### ISSUE TITLE
Command line arguments with spaces within double quote aren't being passed to LabVIEW

### ISSUE THREAD

**Issue by chinghwayu** [JamesMc86/LabVIEW-CLI#4]
Example:

"c:\Program Files (x86)\Wiresmith Technology\LabVIEW CLI\labview-cli.exe" "C:\Documents\GitHub\LabVIEW-CLI\LabVIEW Source\CLI Demo.vi" -- "This is a test"
 
This doesn't pass "This is a test" as a single argument. Instead, it passes each word as a separate argument.

**Comment by JamesMc86** [comment]
The v1.1.0-beta release should fix this issue. You only need to update the C# app for this to work.

Thanks for the report!
