### ISSUE TITLE
 .exe target application not recognized as an executable if .EXE is in uppercase in cmd line

### ISSUE THREAD

**Issue by MattGib** [JamesMc86/LabVIEW-CLI#40]
Example:

labview-cli TARGETAPP.EXE -- arg1=0

In this example the target app is not recognized as an executable because the .exe is in uppercase.

**Comment by JamesMc86** [comment]
Thanks for the pull request on this. I should get it integrated tomorrow.

**Comment by JamesMc86** [comment]
Merged in the fix.

**Comment by MattGib** [comment]
Awesome. Thank you James.
