### ISSUE TITLE
Exit Code is capped at 4927

### ISSUE THREAD

**Issue by MattGib** [JamesMc86/LabVIEW-CLI#42]
Returning an exit code higher than 4927 will return an exit code value of 4927.

Also returning a negative exit code will return an exit code value of 1061109567. 

 Could it be a problem with the byte code conversion?

        public int extractExitCode(string msgData)
        {
            Byte[] codeBytes = new Byte[4];

            codeBytes = Encoding.ASCII.GetBytes(msgData.ToCharArray(0, 4), 0, 4);
            Array.Reverse(codeBytes);

            return BitConverter.ToInt32(codeBytes, 0);

**Comment by JamesMc86** [comment]
Hi Matt,

Thanks for reporting this. It isn't quite as straightforward as that since I have an integration test that runs with an exit code of 10000. I will add a test with a negative number to see what happens there and see if we can track this down.

**Comment by MattGib** [comment]
Hi James,

That is possible. I haven’t tested for all cases. 

 I can’t figure out exactly what is going on. 

Thanks for looking into it. 

Matt

**Comment by JamesMc86** [comment]
This is a representation issue. Changed message format to be a string of the number rather than a flattened binary to make it easier to work with. Will be included in next release.
