### ISSUE TITLE
Not detecting 64-bit LabVIEW

### ISSUE THREAD

**Issue by royalcow** [JamesMc86/LabVIEW-CLI#50]
When trying to launch a VI in the 64-bit version of LabVIEW, I get the following text.

`LabVIEW version "2016 64bit" not found!
Available LabVIEW versions are:
2016 f5, 32bit
2016 f5, 32bit`

One of those 2016 32 bits should be the 64 bit version!

**Comment by JamesMc86** [comment]
Hi royalcow,

Which version are you running? If you use a version after 1.5.0 this issue should have been fixed, but let me know if not.

You can find the latest versions at https://github.com/JamesMc86/LabVIEW-CLI/releases

Cheers,
James

**Comment by royalcow** [comment]
Ahhh! Thank you very much! I had used the version that's published on the VIPM feed (1.4) and not the most recent. Using the most recent seems to clear that up. Thanks again!
