### ISSUE TITLE
`Exit with Error Cluster` missing error code parameter

### ISSUE THREAD

**Issue by wojo1206** [JamesMc86/LabVIEW-CLI#51]
On `Windows 10` after running the msi installer from release `LabVIEW-CLI-1.5.3`, I opened the CLI Demo in `LabVIEW 2018` and noticed that the `Exit with Error Cluster` element doesn't accept the error code parameter. I also noticed that its icon looks odd. Any help on this will be appreciated.

![image](https://image.ibb.co/ijsNYd/labview_cli.png)

**Comment by JamesMc86** [comment]
Hi wojo,

Have you come from an older version?

We found that most people just wanted to use the error code as the exit code so we made the change to what you see there. It will just pull the code from the error cluster hence no additional code input. This was changed in v1.5.0.

The old function should still be available in the palettes though if you wanted to use it.

**Comment by wojo1206** [comment]
No, I am not coming from older version. I simply noticed the difference in error cluster icon between wiki screenshoot and mine and got worried. Good to know the change was intentional. Thanks @JamesMc86
